const slidesData=[
 {name:'Bocas del Toro',sub:'Caribe, aventura y naturaleza',img:'assets/bocas.jpg',desc:'Islas, mar y una vibra caribeña perfecta para desconectarte y vivir nuevas experiencias.'},
 {name:'San Blas',sub:'Paraíso caribeño',img:'assets/sanblas.jpg',desc:'Aguas turquesas, islas de ensueño y cultura Guna en una escapada que se siente única.'},
 {name:'Ciudad de Panamá',sub:'Cultura, historia y modernidad',img:'assets/panama-city.jpg',desc:'City tours, compras, historia y los grandes íconos de la capital en un recorrido a tu medida.'},
 {name:'Valle de Antón',sub:'Naturaleza y tranquilidad',img:'assets/valle.jpg',desc:'Clima fresco, paisajes verdes y experiencias de montaña para respirar diferente.'},
 {name:'Isla Otoque',sub:'Naturaleza, relax y aventura',img:'assets/otoque.jpg',desc:'Mar, playa y naturaleza en el Pacífico panameño con experiencias inolvidables.'}
];
const slides=document.getElementById('heroSlides'),dots=document.getElementById('heroDots'),desc=document.getElementById('heroDescription'),meta=document.getElementById('slideMeta');
if(slides&&dots){let index=0,timer;slidesData.forEach((s,i)=>{const el=document.createElement('div');el.className='slide'+(i===0?' active':'');el.style.backgroundImage=`url('${s.img}')`;slides.appendChild(el);const d=document.createElement('button');d.ariaLabel=`Ir a ${s.name}`;d.className=i===0?'active':'';d.onclick=()=>go(i);dots.appendChild(d)});function render(){[...slides.children].forEach((e,i)=>e.classList.toggle('active',i===index));[...dots.children].forEach((e,i)=>e.classList.toggle('active',i===index));const s=slidesData[index];if(desc)desc.textContent=s.desc;if(meta)meta.innerHTML=`⌖ ${s.name}<small>${s.sub}</small>`}function go(i){index=(i+slidesData.length)%slidesData.length;render();restart()}function restart(){clearInterval(timer);timer=setInterval(()=>go(index+1),5600)}document.querySelector('.prev')?.addEventListener('click',()=>go(index-1));document.querySelector('.next')?.addEventListener('click',()=>go(index+1));restart();}
const tripSearch=document.getElementById('tripSearch');if(tripSearch)tripSearch.addEventListener('submit',e=>{e.preventDefault();const d=document.getElementById('searchDestination').value;const date=document.getElementById('searchDate').value||'por definir';const people=document.getElementById('searchPeople').value;window.open(`https://wa.me/50766687095?text=${encodeURIComponent(`Hola Caribbean Travel, quiero cotizar ${d}. Fecha: ${date}. Viajeros: ${people}.`)}`,'_blank')});
const internationalForm=document.getElementById('internationalForm');if(internationalForm)internationalForm.addEventListener('submit',e=>{e.preventDefault();const c=document.getElementById('intlCountry').value,d=document.getElementById('intlDate').value||'por definir',p=document.getElementById('intlPeople').value,s=document.getElementById('intlStyle').value;window.open(`https://wa.me/50766687095?text=${encodeURIComponent(`Hola Caribbean Travel, quiero organizar un viaje internacional a ${c}. Fecha: ${d}. Viajeros: ${p}. Tipo de viaje: ${s}.`)}`,'_blank')});
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav');
if(toggle&&nav){
  const setMenu=(open)=>{nav.classList.toggle('open',open);toggle.classList.toggle('is-open',open);toggle.setAttribute('aria-expanded',open);document.body.classList.toggle('menu-open',open)};
  toggle.addEventListener('click',()=>setMenu(!nav.classList.contains('open')));
  nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{if(innerWidth<=820)setMenu(false)}));
  document.addEventListener('click',e=>{if(innerWidth<=820&&nav.classList.contains('open')&&!nav.contains(e.target)&&!toggle.contains(e.target))setMenu(false)});
  window.addEventListener('resize',()=>{if(innerWidth>820)setMenu(false)});
}
document.querySelectorAll('.nav-link').forEach(b=>b.addEventListener('click',e=>{if(innerWidth<=820){e.preventDefault();const item=b.parentElement;document.querySelectorAll('.has-dropdown.open').forEach(x=>{if(x!==item)x.classList.remove('open')});item.classList.toggle('open')}}));
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const filter=btn.dataset.filter;document.querySelectorAll('.gallery-item').forEach(item=>item.style.display=(filter==='all'||item.dataset.cat===filter)?'block':'none')}));
document.querySelectorAll('.gallery-shot').forEach(btn=>btn.addEventListener('click',()=>{const img=btn.querySelector('img');const modal=document.createElement('div');modal.className='lightbox';modal.innerHTML=`<button aria-label="Cerrar">×</button><img src="${img.src}" alt="${img.alt}">`;document.body.appendChild(modal);modal.addEventListener('click',()=>modal.remove())}));
